"""
ICP wizard — the "guided interview" the spec calls for: "An ICP definition
file... a guided wizard builds it in an interview."

Split the same way as review_queue.py: `build_icp_dict()` is a pure function
(answers dict -> icp dict, fully unit-testable), `run_wizard()` is the thin
interactive CLI shell around it.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

import yaml

DEFAULT_WEIGHTS = {
    "industry_match": 35,
    "size_match": 20,
    "geography_match": 15,
    "trigger_signal_strength": 30,
}


def _split_csv(raw: str) -> list[str]:
    return [item.strip() for item in raw.split(",") if item.strip()]


def build_icp_dict(answers: dict[str, Any]) -> dict[str, Any]:
    """answers keys: business_name, what_we_sell, industries (csv str or list),
    min_employees, max_employees, geography (csv), trigger_signals (csv),
    exclude (csv), match_threshold, maybe_threshold, cost_comparison (optional)."""

    def as_list(key: str) -> list[str]:
        value = answers.get(key, "")
        return value if isinstance(value, list) else _split_csv(str(value))

    icp: dict[str, Any] = {
        "business": {
            "name": answers.get("business_name", "").strip(),
            "what_we_sell": answers.get("what_we_sell", "").strip(),
        },
        "target": {
            "industries": as_list("industries"),
            "company_size": {
                "min_employees": int(answers.get("min_employees") or 1),
                "max_employees": int(answers.get("max_employees") or 500),
            },
            "geography": as_list("geography"),
            "trigger_signals": as_list("trigger_signals"),
            "exclude": as_list("exclude"),
        },
        "scoring": {
            "match_threshold": float(answers.get("match_threshold") or 70),
            "maybe_threshold": float(answers.get("maybe_threshold") or 40),
            "weights": dict(DEFAULT_WEIGHTS),
        },
    }
    cost_comparison = str(answers.get("cost_comparison", "")).strip()
    if cost_comparison:
        icp["cost_comparison"] = cost_comparison
    return icp


def write_icp(icp: dict[str, Any], out_path: str | Path) -> Path:
    path = Path(out_path)
    path.parent.mkdir(parents=True, exist_ok=True)
    header = (
        "# Generated by `python3 run.py wizard`. Edit freely — this is a plain yaml file,\n"
        "# not a black box. See config/icp.example.yaml for a fully-commented reference.\n\n"
    )
    path.write_text(header + yaml.safe_dump(icp, sort_keys=False, default_flow_style=False))
    return path


def run_wizard(out_path: str | Path = "config/icp.yaml") -> Path:
    print("Outbound Engine — ICP wizard\n" + "-" * 40)
    print("A few questions to build your Ideal Customer Profile. Comma-separate lists.\n")

    answers = {
        "business_name": input("Your agency's name: ").strip(),
        "what_we_sell": input("What you sell (one line, e.g. 'SEO + paid media for local service businesses'): ").strip(),
        "industries": input("Target industries (comma-separated, e.g. 'home services, legal, healthcare'): ").strip(),
        "min_employees": input("Minimum company size (employees) [1]: ").strip() or "1",
        "max_employees": input("Maximum company size (employees) [500]: ").strip() or "500",
        "geography": input("Geography (comma-separated, e.g. 'United States'): ").strip(),
        "trigger_signals": input(
            "Trigger signals worth reaching out on (comma-separated, e.g. "
            "'visited pricing page, returned visitor, came from paid search'): "
        ).strip(),
        "exclude": input("Anything to always exclude (comma-separated, e.g. 'competitor agencies, students'): ").strip(),
        "match_threshold": input("Score (0-100) that counts as a strong match [70]: ").strip() or "70",
        "maybe_threshold": input("Score (0-100) below which it's a reject [40]: ").strip() or "40",
        "cost_comparison": input(
            "Optional: what did/will this replace in tool spend? (for the weekly report, e.g. "
            "'Replaces ~$700/mo Apollo + Hunter.io spend') [skip]: "
        ).strip(),
    }

    icp = build_icp_dict(answers)
    path = write_icp(icp, out_path)
    print(f"\nSaved {path}. Now add 2-3 real outreach examples to config/voice-examples.md, "
          f"then run: python3 run.py pipeline --dry-run")
    return path
